services:
  - type: web
    name: sanjusxrx
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx srvx --prod -s dist/client dist/server/server.js
    envVars:
      - key: NODE_ENV
        value: production
