/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ThreatModelRouteImport } from './routes/threat-model'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RealtimeRouteImport } from './routes/realtime'
import { Route as DedicationRouteImport } from './routes/dedication'
import { Route as BirthdayRouteImport } from './routes/birthday'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatModelRoute = ThreatModelRouteImport.update({
  id: '/threat-model',
  path: '/threat-model',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtimeRoute = RealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const DedicationRoute = DedicationRouteImport.update({
  id: '/dedication',
  path: '/dedication',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayRoute = BirthdayRouteImport.update({
  id: '/birthday',
  path: '/birthday',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/birthday': typeof BirthdayRoute
  '/dedication': typeof DedicationRoute
  '/realtime': typeof RealtimeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/threat-model': typeof ThreatModelRoute
  '/vault': typeof VaultRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/birthday': typeof BirthdayRoute
  '/dedication': typeof DedicationRoute
  '/realtime': typeof RealtimeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/threat-model': typeof ThreatModelRoute
  '/vault': typeof VaultRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/birthday': typeof BirthdayRoute
  '/dedication': typeof DedicationRoute
  '/realtime': typeof RealtimeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/threat-model': typeof ThreatModelRoute
  '/vault': typeof VaultRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/birthday'
    | '/dedication'
    | '/realtime'
    | '/sitemap.xml'
    | '/threat-model'
    | '/vault'
    | '/whitepaper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/birthday'
    | '/dedication'
    | '/realtime'
    | '/sitemap.xml'
    | '/threat-model'
    | '/vault'
    | '/whitepaper'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/birthday'
    | '/dedication'
    | '/realtime'
    | '/sitemap.xml'
    | '/threat-model'
    | '/vault'
    | '/whitepaper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BirthdayRoute: typeof BirthdayRoute
  DedicationRoute: typeof DedicationRoute
  RealtimeRoute: typeof RealtimeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThreatModelRoute: typeof ThreatModelRoute
  VaultRoute: typeof VaultRoute
  WhitepaperRoute: typeof WhitepaperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-model': {
      id: '/threat-model'
      path: '/threat-model'
      fullPath: '/threat-model'
      preLoaderRoute: typeof ThreatModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtime': {
      id: '/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof RealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dedication': {
      id: '/dedication'
      path: '/dedication'
      fullPath: '/dedication'
      preLoaderRoute: typeof DedicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday': {
      id: '/birthday'
      path: '/birthday'
      fullPath: '/birthday'
      preLoaderRoute: typeof BirthdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  BirthdayRoute: BirthdayRoute,
  DedicationRoute: DedicationRoute,
  RealtimeRoute: RealtimeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThreatModelRoute: ThreatModelRoute,
  VaultRoute: VaultRoute,
  WhitepaperRoute: WhitepaperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
